// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNt3vvjxHvRQuk9krFeHDB1M0VxjIvYYo',
    appId: '1:53598013459:web:af5268a827d7d1f820d7e6',
    messagingSenderId: '53598013459',
    projectId: 'linkod-db',
    authDomain: 'linkod-db.firebaseapp.com',
    storageBucket: 'linkod-db.firebasestorage.app',
    measurementId: 'G-3C0PCX6DP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOTt49luTHZqaYW1zn63acmH8d7pUpkfA',
    appId: '1:53598013459:android:15a5e0e463a7d15620d7e6',
    messagingSenderId: '53598013459',
    projectId: 'linkod-db',
    storageBucket: 'linkod-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXOrJVjC18iDFjcSOkxNyVb8F-93pRMJ4',
    appId: '1:53598013459:ios:cc4ae0994c0b166620d7e6',
    messagingSenderId: '53598013459',
    projectId: 'linkod-db',
    storageBucket: 'linkod-db.firebasestorage.app',
    iosBundleId: 'com.example.linkodAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXOrJVjC18iDFjcSOkxNyVb8F-93pRMJ4',
    appId: '1:53598013459:ios:cc4ae0994c0b166620d7e6',
    messagingSenderId: '53598013459',
    projectId: 'linkod-db',
    storageBucket: 'linkod-db.firebasestorage.app',
    iosBundleId: 'com.example.linkodAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNt3vvjxHvRQuk9krFeHDB1M0VxjIvYYo',
    appId: '1:53598013459:web:5d49c7aa69c3f7de20d7e6',
    messagingSenderId: '53598013459',
    projectId: 'linkod-db',
    authDomain: 'linkod-db.firebaseapp.com',
    storageBucket: 'linkod-db.firebasestorage.app',
    measurementId: 'G-2DQW4SDET2',
  );
}

